/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JoshuaDuPlessis;

import java.awt.Color;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.util.Date;
import java.util.Random;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
   
        initComponents();
        pnlClasses.
                setVisible(false);
        pnlAssignments.
                setVisible(false);
        pnlClassroom.
                setVisible(false);
        btnRegister.
                setVisible(true);
        btnLogin.
                setVisible(true);
        btnExit.
                setVisible(true);
        pnlAssignments.
                setBackground(Color.BLACK);
        btnAgreement.
                setVisible(false);
        btnValidate.
                setVisible(false);
        btnAssignments.
                setVisible(false);
        btnClasses.
                setVisible(false);
        lblUsername.
                setVisible(false);
        lblPassword.
                setVisible(false);
        jLabel5.
                setVisible(false);
        jLabel6.
                setVisible(false);
        lblAgreement.
                setVisible(false);
        lblErrorAge.
                setVisible(false);
        lblErrorDate.
                setVisible(false);
        lblFeedback.
                setVisible(false);
        lblFeedback2.
                setVisible(false);
        spnAge.
                setVisible(false);
        txtPassword.
                setVisible(false);
        txtUsername.
                setVisible(false);
        yrValue.
                setVisible(false);
    }//VISIBLE STUFF

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlClassroom = new javax.swing.JPanel();
        lblHeadingPage = new javax.swing.JLabel();
        btnClasses = new javax.swing.JButton();
        btnAssignments = new javax.swing.JButton();
        pnlHome = new javax.swing.JPanel();
        lblFeedback = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnValidate = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        yrValue = new com.toedter.calendar.JDateChooser();
        spnAge = new javax.swing.JSpinner();
        lblHeader = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnAgreement = new javax.swing.JCheckBox();
        lblAgreement = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblFeedback2 = new javax.swing.JLabel();
        lblErrorAge = new javax.swing.JLabel();
        lblErrorDate = new javax.swing.JLabel();
        pnlAssignments = new javax.swing.JPanel();
        spAssignment1 = new javax.swing.JScrollPane();
        taAssignment1 = new javax.swing.JTextArea();
        spAssignment2 = new javax.swing.JScrollPane();
        taAssignment2 = new javax.swing.JTextArea();
        spAssignment3 = new javax.swing.JScrollPane();
        taAssignment3 = new javax.swing.JTextArea();
        spAssignment4 = new javax.swing.JScrollPane();
        taAssignment4 = new javax.swing.JTextArea();
        btnTest = new javax.swing.JButton();
        btnTest2 = new javax.swing.JButton();
        btnTest3 = new javax.swing.JButton();
        btnTest4 = new javax.swing.JButton();
        lblAssignment1 = new javax.swing.JLabel();
        lblAssignment2 = new javax.swing.JLabel();
        lblAssignment3 = new javax.swing.JLabel();
        lblAssignment4 = new javax.swing.JLabel();
        btnAssignment1 = new javax.swing.JButton();
        btnAssignment2 = new javax.swing.JButton();
        btnAssignment3 = new javax.swing.JButton();
        btnAssignment4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlClasses = new javax.swing.JPanel();
        lblClasses = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(960, 540));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));

        lblHeadingPage.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHeadingPage.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadingPage.setText("JClassroom");

        btnClasses.setBackground(new java.awt.Color(0, 0, 0));
        btnClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClasses.setForeground(new java.awt.Color(255, 255, 255));
        btnClasses.setText("Classes");
        btnClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassesActionPerformed(evt);
            }
        });

        btnAssignments.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignments.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignments.setText("Assignments");
        btnAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClassroomLayout = new javax.swing.GroupLayout(pnlClassroom);
        pnlClassroom.setLayout(pnlClassroomLayout);
        pnlClassroomLayout.setHorizontalGroup(
            pnlClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassroomLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(pnlClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClassroomLayout.createSequentialGroup()
                        .addComponent(btnAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(btnClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(pnlClassroomLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblHeadingPage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlClassroomLayout.setVerticalGroup(
            pnlClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassroomLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblHeadingPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pnlClassroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
        );

        pnlHome.setBackground(new java.awt.Color(0, 0, 0));
        pnlHome.setMinimumSize(new java.awt.Dimension(700, 500));
        pnlHome.setPreferredSize(new java.awt.Dimension(700, 500));

        txtUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnValidate.setBackground(new java.awt.Color(0, 0, 0));
        btnValidate.setForeground(new java.awt.Color(255, 255, 255));
        btnValidate.setText("Sign In");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        yrValue.setBackground(new java.awt.Color(0, 0, 0));
        yrValue.setForeground(new java.awt.Color(255, 255, 255));

        spnAge.setOpaque(true);

        lblHeader.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("JClassroom");

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("YoB:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age:");

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnAgreement.setForeground(new java.awt.Color(255, 255, 255));
        btnAgreement.setText("Licence Agreement");
        btnAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreementActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 0, 0));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlHomeLayout.createSequentialGroup()
                            .addComponent(lblUsername)
                            .addGap(18, 18, 18)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHomeLayout.createSequentialGroup()
                            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(50, 50, 50))
                                    .addGroup(pnlHomeLayout.createSequentialGroup()
                                        .addComponent(lblPassword)
                                        .addGap(21, 21, 21)))
                                .addGroup(pnlHomeLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(50, 50, 50)))
                            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlHomeLayout.createSequentialGroup()
                                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblErrorAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(pnlHomeLayout.createSequentialGroup()
                                    .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yrValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblErrorDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFeedback2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(pnlHomeLayout.createSequentialGroup()
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnValidate, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAgreement)))
                .addGap(200, 200, 200))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblAgreement))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblHeader)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFeedback2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(yrValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(btnAgreement)
                .addGap(34, 34, 34)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnExit)
                    .addComponent(btnRegister))
                .addGap(51, 51, 51)
                .addComponent(btnValidate)
                .addGap(28, 28, 28)
                .addComponent(lblAgreement)
                .addGap(106, 106, 106))
        );

        taAssignment1.setBackground(new java.awt.Color(0, 0, 0));
        taAssignment1.setColumns(20);
        taAssignment1.setForeground(new java.awt.Color(255, 255, 255));
        taAssignment1.setRows(5);
        spAssignment1.setViewportView(taAssignment1);

        taAssignment2.setBackground(new java.awt.Color(0, 0, 0));
        taAssignment2.setColumns(20);
        taAssignment2.setForeground(new java.awt.Color(255, 255, 255));
        taAssignment2.setRows(5);
        spAssignment2.setViewportView(taAssignment2);

        taAssignment3.setEditable(false);
        taAssignment3.setBackground(new java.awt.Color(0, 0, 0));
        taAssignment3.setColumns(20);
        taAssignment3.setForeground(new java.awt.Color(255, 255, 255));
        taAssignment3.setRows(5);
        spAssignment3.setViewportView(taAssignment3);

        taAssignment4.setBackground(new java.awt.Color(0, 0, 0));
        taAssignment4.setColumns(20);
        taAssignment4.setForeground(new java.awt.Color(255, 255, 255));
        taAssignment4.setRows(5);
        spAssignment4.setViewportView(taAssignment4);

        btnTest.setBackground(new java.awt.Color(0, 0, 0));
        btnTest.setForeground(new java.awt.Color(255, 255, 255));
        btnTest.setText("jButton1");
        btnTest.setBorderPainted(false);
        btnTest.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnTest2.setBackground(new java.awt.Color(0, 0, 0));
        btnTest2.setForeground(new java.awt.Color(255, 255, 255));
        btnTest2.setText("jButton1");
        btnTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest2ActionPerformed(evt);
            }
        });

        btnTest3.setBackground(new java.awt.Color(0, 0, 0));
        btnTest3.setForeground(new java.awt.Color(255, 255, 255));
        btnTest3.setText("btn");
        btnTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest3ActionPerformed(evt);
            }
        });

        btnTest4.setBackground(new java.awt.Color(0, 0, 0));
        btnTest4.setForeground(new java.awt.Color(255, 255, 255));
        btnTest4.setText("jButton3");
        btnTest4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest4ActionPerformed(evt);
            }
        });

        lblAssignment1.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignment1.setText("Assignment 1");

        lblAssignment2.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignment2.setText("Assignment 2");

        lblAssignment3.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignment3.setText("Assignment 3");

        lblAssignment4.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignment4.setText("Assignment 4");

        btnAssignment1.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignment1.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignment1.setText("Submit");
        btnAssignment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignment1ActionPerformed(evt);
            }
        });

        btnAssignment2.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignment2.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignment2.setText("Submit");
        btnAssignment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignment2ActionPerformed(evt);
            }
        });

        btnAssignment3.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignment3.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignment3.setText("Submit");
        btnAssignment3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignment3ActionPerformed(evt);
            }
        });

        btnAssignment4.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignment4.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignment4.setText("Submit");
        btnAssignment4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignment4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assignments");

        javax.swing.GroupLayout pnlAssignmentsLayout = new javax.swing.GroupLayout(pnlAssignments);
        pnlAssignments.setLayout(pnlAssignmentsLayout);
        pnlAssignmentsLayout.setHorizontalGroup(
            pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addComponent(btnTest4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addComponent(lblAssignment4))
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAssignment4)))
                        .addGap(18, 18, 18)
                        .addComponent(spAssignment4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addComponent(btnTest3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAssignment3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAssignmentsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAssignment3)))
                        .addGap(18, 18, 18)
                        .addComponent(spAssignment3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addComponent(btnTest2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAssignment2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAssignmentsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAssignment2)))
                        .addGap(18, 18, 18)
                        .addComponent(spAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAssignment1))
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                                .addComponent(btnTest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAssignment1)))
                        .addGap(18, 18, 18)
                        .addComponent(spAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        pnlAssignmentsLayout.setVerticalGroup(
            pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTest)
                            .addComponent(lblAssignment1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnAssignment1))
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(spAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAssignment2)
                            .addComponent(btnTest2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssignment2)))
                .addGap(18, 18, 18)
                .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spAssignment3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAssignment3)
                            .addComponent(btnTest3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssignment3)))
                .addGap(18, 18, 18)
                .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spAssignment4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAssignment4)
                            .addComponent(btnTest4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssignment4)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        lblClasses.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblClasses.setForeground(new java.awt.Color(255, 255, 255));
        lblClasses.setText("Classes:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout pnlClassesLayout = new javax.swing.GroupLayout(pnlClasses);
        pnlClasses.setLayout(pnlClassesLayout);
        pnlClassesLayout.setHorizontalGroup(
            pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassesLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClassesLayout.createSequentialGroup()
                        .addComponent(lblClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClassesLayout.createSequentialGroup()
                        .addGroup(pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlClassesLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlClassesLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlClassesLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))))
        );
        pnlClassesLayout.setVerticalGroup(
            pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlClassroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAssignments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlClassroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAssignments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsActionPerformed

      pnlAssignments.setVisible(true);
        pnlClassroom.setVisible(false);
        pnlClassroom.setBackground(Color.BLACK);
        btnAssignments.setVisible(false);
        btnClasses.setVisible(false);
        lblHeadingPage.setVisible(false);
       
    }//GEN-LAST:event_btnAssignmentsActionPerformed

    private void btnClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassesActionPerformed
       pnlClassroom.setVisible(false);
       pnlClasses.setVisible(true);
    }//GEN-LAST:event_btnClassesActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        pnlHome.setVisible(false);
        pnlClassroom.setVisible(true);
        pnlClassroom.setBackground(Color.BLACK);
        btnAssignments.setVisible(true);
        btnClasses.setVisible(true);
        lblHeadingPage.setVisible(true);

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        btnRegister.setVisible(false);
        btnLogin.setVisible(false);
        btnExit.setVisible(false);
        btnAgreement.setVisible(true);
        btnValidate.setVisible(true);

        lblUsername.setVisible(true);
        lblPassword.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        // jPanel2.setVisible(true);
        lblAgreement.setVisible(true);
        lblErrorAge.setVisible(true);
        lblErrorDate.setVisible(true);
        lblFeedback.setVisible(true);
        lblFeedback2.setVisible(true);
        spnAge.setVisible(true);
        yrValue.setVisible(true);
        txtUsername.setVisible(true);
        txtPassword.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnAgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgreementActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        txtUsername.setVisible(true);
        txtPassword.setVisible(true);
        btnValidate.setVisible(true);
        lblPassword.setVisible(true);
        lblUsername.setVisible(true);
        btnExit.setVisible(true);
        btnRegister.setVisible(false);
        btnLogin.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        // TODO add your handling code here:

        String tempUser = txtUsername.getText();
        if (tempUser.isEmpty()) {

            lblFeedback.setText("you must enter a username");

        }else if (tempUser.length() < 5)
        {
            lblFeedback.setText("Your username does not exist");
            lblFeedback.setForeground(Color.RED);
        } else {
            lblFeedback.setText("Username is valid!");
            lblFeedback.setForeground(Color.GREEN);

            String tempPass = txtPassword.getText();
            Pattern p = Pattern.compile("[^A-Za-z0-9 ]");
            Matcher m = p.matcher(tempPass);

            if (tempPass.isEmpty()) {

                lblFeedback2.setText("You forgot to enter your password");

            }else if(tempPass.length() < 6){
                lblFeedback2.setText("Your password is too short");
                lblFeedback2.setForeground(Color.RED);

            }else if(m.find()){
                lblFeedback2.setText("Your password is secure enough");
                lblFeedback2.setForeground(Color.GREEN);
            }

            else {
                lblFeedback2.setText("Password is not secure enough");
                lblFeedback2.setForeground(Color.RED);
            }

            int tempAge;

            tempAge = Integer.parseInt(spnAge.getValue().toString());

            if (tempAge > 99 || tempAge <13 ) {

                lblErrorAge.setText("Age is invalid");
                lblErrorAge.setForeground(Color.RED);

            }else{
                lblErrorAge.setText("Age is valid");
                lblErrorAge.setForeground(Color.GREEN);
            }

            Date d = new Date();
            int year = d.getYear();
            int CurrentYear = year + 1900;
            int tempYear;

            tempYear = 1900 + yrValue.getDate().getYear();

            if (tempYear + tempAge != CurrentYear) {
                lblErrorDate.setText("The date is incorrect");
                lblErrorDate.setForeground(Color.RED);

            }else {
                lblErrorDate.setText("The date is correct");
                lblErrorDate.setForeground(Color.GREEN);
            }

            if (btnAgreement.isSelected()) {

            }else   {
                lblAgreement.setText("You have to agree");
                lblAgreement.setForeground(Color.RED);
            }

        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
     
        btnTest.setVisible(false);
        
        Random rd = new Random();
     
     
   
       String month = "";
      int day =  rd.nextInt(1,32);
       int year = 2023;
       
            String subject = "";
        
       int number = (int)(Math.random() * 12) + 1;
       if (number == 1) 
       {
      month = "Januaray"; 
      subject = "English";
       }
    else if (number == 2) 
    {
      month = "Feburary";
      subject = "English";
    }
    else if (number == 3) {
      month = "March";
    subject = "Afrikaans";}
    else if (number == 4){ 
      month = "April";
    subject = "Physics";}
    else if (number == 5){ 
      month = "May";
    subject = "IT";}
    else if (number == 6) {
      month = "June";
    subject = "CAT";}
    else if (number == 7){ 
      month = "July";
    subject = "Maths";}
    else if (number == 8) {
      month = "August";
    subject = "Geography";}
    else if (number == 9){ 
      month = "September";
    subject = "History";}
    else if (number == 10) {
      month = "October";
     subject = "LO";}
    else if (number == 11){ 
      month = "November";
    subject = "Accounting";}
    else if (number == 12){ 
      month = "December";
    subject = "Biology";}
           
        taAssignment1.setText("Assignment Due : "+ day + " " +
                month + " "+ year +"\n"+ "---------------------"+"\n"+
                        "    "+subject+""+"\n"+"---------------------" );
         
              
              
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest2ActionPerformed
 
         btnTest2.setVisible(false);
        Random rd = new Random();
     
       String subject = "";
   
       String month = "";
      int day =  rd.nextInt(1,32);
       int year = 2023;
       
            
        
       int number = (int)(Math.random() * 12) + 1;
          if (number == 1) 
       {
      month = "Januaray"; 
      subject = "English";
       }
    else if (number == 2) 
    {
      month = "Feburary";
      subject = "English";
    }
    else if (number == 3) {
      month = "March";
    subject = "Afrikaans";}
    else if (number == 4){ 
      month = "April";
    subject = "Physics";}
    else if (number == 5){ 
      month = "May";
    subject = "IT";}
    else if (number == 6) {
      month = "June";
    subject = "CAT";}
    else if (number == 7){ 
      month = "July";
    subject = "Maths";}
    else if (number == 8) {
      month = "August";
    subject = "Geography";}
    else if (number == 9){ 
      month = "September";
    subject = "History";}
    else if (number == 10) {
      month = "October";
     subject = "LO";}
    else if (number == 11){ 
      month = "November";
    subject = "Accounting";}
    else if (number == 12){ 
      month = "December";
    subject = "Biology";}
           
           
          taAssignment2.setText("Assignment Due : "+ day + " " +
                month + " "+ year +"\n"+ "---------------------"+"\n"+
                        "    "+subject+""+"\n"+"---------------------" );
              
                     
    }//GEN-LAST:event_btnTest2ActionPerformed

    private void btnTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest3ActionPerformed

 btnTest3.setVisible(false);

        Random rd = new Random();
     
     
     String subject = "";
       String month = "";
      int day =  rd.nextInt(1,32);
       int year = 2023;
       
            
        
       int number = (int)(Math.random() * 12) + 1;
           if (number == 1) 
       {
      month = "Januaray"; 
      subject = "English";
       }
    else if (number == 2) 
    {
      month = "Feburary";
      subject = "English";
    }
    else if (number == 3) {
      month = "March";
    subject = "Afrikaans";}
    else if (number == 4){ 
      month = "April";
    subject = "Physics";}
    else if (number == 5){ 
      month = "May";
    subject = "IT";}
    else if (number == 6) {
      month = "June";
    subject = "CAT";}
    else if (number == 7){ 
      month = "July";
    subject = "Maths";}
    else if (number == 8) {
      month = "August";
    subject = "Geography";}
    else if (number == 9){ 
      month = "September";
    subject = "History";}
    else if (number == 10) {
      month = "October";
     subject = "LO";}
    else if (number == 11){ 
      month = "November";
    subject = "Accounting";}
    else if (number == 12){ 
      month = "December";
    subject = "Biology";}
           
           
        
                 taAssignment3.setText("Assignment Due : "+ day + " " +
                month + " "+ year +"\n"+ "---------------------"+"\n"+
                        "    "+subject+""+"\n"+"---------------------" );
              
    }//GEN-LAST:event_btnTest3ActionPerformed

    private void btnTest4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest4ActionPerformed
 btnTest4.setVisible(false);
        
        Random rd = new Random();
     
     
   
       String month = "";
      int day =  rd.nextInt(1,32);
       int year = 2023;
       
            String subject = "";  
        
       int number = (int)(Math.random() * 12) + 1;
            if (number == 1) 
       {
      month = "Januaray"; 
      subject = "English";
       }
    else if (number == 2) 
    {
      month = "Feburary";
      subject = "English";
    }
    else if (number == 3) {
      month = "March";
    subject = "Afrikaans";}
    else if (number == 4){ 
      month = "April";
    subject = "Physics";}
    else if (number == 5){ 
      month = "May";
    subject = "IT";}
    else if (number == 6) {
      month = "June";
    subject = "CAT";}
    else if (number == 7){ 
      month = "July";
    subject = "Maths";}
    else if (number == 8) {
      month = "August";
    subject = "Geography";}
    else if (number == 9){ 
      month = "September";
    subject = "History";}
    else if (number == 10) {
      month = "October";
     subject = "LO";}
    else if (number == 11){ 
      month = "November";
    subject = "Accounting";}
    else if (number == 12){ 
      month = "December";
    subject = "Biology";}
           
           
           taAssignment4.setText("Assignment Due : "+ day + " " +
                month + " "+ year +"\n"+ "---------------------"+"\n"+
                        "    "+subject+""+"\n"+"---------------------" );
              
              
    }//GEN-LAST:event_btnTest4ActionPerformed

    private void btnAssignment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignment1ActionPerformed
      String temp = taAssignment1.getText();
      String submitted = "\n Submitted!";
       taAssignment1.setText(temp + submitted);
    }//GEN-LAST:event_btnAssignment1ActionPerformed

    private void btnAssignment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignment2ActionPerformed
       String temp = taAssignment2.getText();
       String submitted = "\n Submitted!";
       
       taAssignment2.setText(temp + submitted);
    }//GEN-LAST:event_btnAssignment2ActionPerformed

    private void btnAssignment3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignment3ActionPerformed
         String temp = taAssignment3.getText();
      String submitted = "\n Submitted!";
       taAssignment3.setText(temp + submitted);
    }//GEN-LAST:event_btnAssignment3ActionPerformed

    private void btnAssignment4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignment4ActionPerformed
        String temp = taAssignment4.getText();
      String submitted = "\n Submitted!";
       taAssignment4.setText(temp + submitted);
    }//GEN-LAST:event_btnAssignment4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAgreement;
    private javax.swing.JButton btnAssignment1;
    private javax.swing.JButton btnAssignment2;
    private javax.swing.JButton btnAssignment3;
    private javax.swing.JButton btnAssignment4;
    private javax.swing.JButton btnAssignments;
    private javax.swing.JButton btnClasses;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnTest2;
    private javax.swing.JButton btnTest3;
    private javax.swing.JButton btnTest4;
    private javax.swing.JButton btnValidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JLabel lblAgreement;
    private javax.swing.JLabel lblAssignment1;
    private javax.swing.JLabel lblAssignment2;
    private javax.swing.JLabel lblAssignment3;
    private javax.swing.JLabel lblAssignment4;
    private javax.swing.JLabel lblClasses;
    private javax.swing.JLabel lblErrorAge;
    private javax.swing.JLabel lblErrorDate;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblFeedback2;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeadingPage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlAssignments;
    private javax.swing.JPanel pnlClasses;
    private javax.swing.JPanel pnlClassroom;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JScrollPane spAssignment1;
    private javax.swing.JScrollPane spAssignment2;
    private javax.swing.JScrollPane spAssignment3;
    private javax.swing.JScrollPane spAssignment4;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextArea taAssignment1;
    private javax.swing.JTextArea taAssignment2;
    private javax.swing.JTextArea taAssignment3;
    private javax.swing.JTextArea taAssignment4;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private com.toedter.calendar.JDateChooser yrValue;
    // End of variables declaration//GEN-END:variables
}
