/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JoshuaDuPlessis;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTabbedPane;
import javax.swing.ListSelectionModel;

    
 
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class NewGUI extends javax.swing.JFrame {

   StorageDatabase storage = new StorageDatabase();   

    /**
     * Creates new form NewGUI
     */
    public NewGUI() {
         
        initComponents();
        
    pnlRegister.setVisible(false);
    pnlLogin.setVisible(false);
    pnlMenuStudent.setVisible(false);
    pnlMenuTeacher.setVisible(false);
    pnlClassesStudent.setVisible(false);
    pnlClassesTeacher.setVisible(false);
    pnlCreateClasses.setVisible(false);
	  btnAddAssignment.setContentAreaFilled(false);
      btnAssignments.setContentAreaFilled(false);
      btnAssignments1.setContentAreaFilled(false);
      btnClasses.setContentAreaFilled(false);
      btnClasses1.setContentAreaFilled(false);
      btnCreate.setContentAreaFilled(false);
      btnExit.setContentAreaFilled(false);
      btnLogin.setContentAreaFilled(false);
      btnLoginCheck.setContentAreaFilled(false);
      btnNewClass.setContentAreaFilled(false);
      btnRegister.setContentAreaFilled(false);
      btnValidate.setContentAreaFilled(false);
      pnlCreateAssignments.setVisible(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        yrValue = new com.toedter.calendar.JDateChooser();
        spnAge = new javax.swing.JSpinner();
        lblHeader = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgreement = new javax.swing.JCheckBox();
        txtUsername = new javax.swing.JTextField();
        btnValidate = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        pnlLogin = new javax.swing.JPanel();
        txtUsername1 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JTextField();
        lblHeader1 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        btnLoginCheck = new javax.swing.JButton();
        pnlMenuStudent = new javax.swing.JPanel();
        lblHeadingPage = new javax.swing.JLabel();
        btnClasses = new javax.swing.JButton();
        btnAssignments = new javax.swing.JButton();
        pnlMenuTeacher = new javax.swing.JPanel();
        lblHeadingPage1 = new javax.swing.JLabel();
        btnClasses1 = new javax.swing.JButton();
        btnAssignments1 = new javax.swing.JButton();
        btnAddAssignment = new javax.swing.JButton();
        btnNewClass = new javax.swing.JButton();
        pnlCreateClasses = new javax.swing.JPanel();
        txtClassName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        txtClassSubject = new javax.swing.JTextField();
        lblClassName = new javax.swing.JLabel();
        lblClassSubject = new javax.swing.JLabel();
        pnlCreateClassesScrollPanel = new javax.swing.JScrollPane();
        jLClassList = new javax.swing.JList<>();
        lblClassSubject1 = new javax.swing.JLabel();
        pnlCreateAssignments = new javax.swing.JPanel();
        lblAssignToClasses = new javax.swing.JLabel();
        txtAssignmentTitle = new javax.swing.JTextField();
        btnCreateAssignment = new javax.swing.JButton();
        lblAssignmentTitle = new javax.swing.JLabel();
        lblAssignmentDesc = new javax.swing.JLabel();
        pnlCreateClassesScrollPanel1 = new javax.swing.JScrollPane();
        jlTeacherClasses = new javax.swing.JList<>();
        txtAssignmentDesc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdcDueDate = new com.toedter.calendar.JDateChooser();
        lblAssignmentDueDate = new javax.swing.JLabel();
        pnlClassesStudent = new javax.swing.JPanel();
        pnlClassesTeacher = new javax.swing.JPanel();
        spTeacherClasses = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JClassroom");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        setName("JClassroom"); // NOI18N
        setSize(new java.awt.Dimension(500, 700));

        pnlHome.setBackground(new java.awt.Color(0, 0, 0));
        pnlHome.setForeground(new java.awt.Color(255, 255, 255));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 0, 0));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JClassroom");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(270, 270, 270))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        pnlRegister.setBackground(new java.awt.Color(0, 0, 0));
        pnlRegister.setForeground(new java.awt.Color(255, 255, 255));

        yrValue.setBackground(new java.awt.Color(0, 0, 0));
        yrValue.setForeground(new java.awt.Color(255, 255, 255));

        spnAge.setOpaque(true);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("JClassroom");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("YoB:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age:");

        btnAgreement.setForeground(new java.awt.Color(255, 255, 255));
        btnAgreement.setText("Teacher?");
        btnAgreement.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        btnAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreementActionPerformed(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnValidate.setBackground(new java.awt.Color(0, 0, 0));
        btnValidate.setForeground(new java.awt.Color(255, 255, 255));
        btnValidate.setText("Register");
        btnValidate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlRegisterLayout.createSequentialGroup()
                            .addComponent(lblUsername)
                            .addGap(18, 18, 18)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnValidate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21)
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnAge, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(yrValue, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(btnAgreement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(lblHeader))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblHeader)
                .addGap(38, 38, 38)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(yrValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spnAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgreement, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnValidate)
                .addGap(82, 82, 82))
        );

        pnlLogin.setBackground(new java.awt.Color(0, 0, 0));
        pnlLogin.setForeground(new java.awt.Color(255, 255, 255));

        txtUsername1.setBackground(new java.awt.Color(0, 0, 0));
        txtUsername1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });

        txtPassword1.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword1.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassword1ActionPerformed(evt);
            }
        });

        lblHeader1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblHeader1.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader1.setText("JClassroom");

        lblUsername1.setBackground(new java.awt.Color(0, 0, 0));
        lblUsername1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Username:");

        lblPassword1.setBackground(new java.awt.Color(0, 0, 0));
        lblPassword1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Password:");

        btnLoginCheck.setBackground(new java.awt.Color(0, 0, 0));
        btnLoginCheck.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginCheck.setText("Login");
        btnLoginCheck.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLoginCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblPassword1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(lblUsername1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLoginCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(lblHeader1)
                .addGap(271, 271, 271))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblHeader1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword1))
                .addGap(18, 18, 18)
                .addComponent(btnLoginCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        pnlMenuStudent.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenuStudent.setForeground(new java.awt.Color(255, 255, 255));

        lblHeadingPage.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHeadingPage.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadingPage.setText("JClassroom");

        btnClasses.setBackground(new java.awt.Color(0, 0, 0));
        btnClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClasses.setForeground(new java.awt.Color(255, 255, 255));
        btnClasses.setText("Classes");
        btnClasses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassesActionPerformed(evt);
            }
        });

        btnAssignments.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignments.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignments.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignments.setText("Assignments");
        btnAssignments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuStudentLayout = new javax.swing.GroupLayout(pnlMenuStudent);
        pnlMenuStudent.setLayout(pnlMenuStudentLayout);
        pnlMenuStudentLayout.setHorizontalGroup(
            pnlMenuStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuStudentLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(lblHeadingPage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMenuStudentLayout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(btnAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(btnClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        pnlMenuStudentLayout.setVerticalGroup(
            pnlMenuStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuStudentLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblHeadingPage)
                .addGap(87, 87, 87)
                .addGroup(pnlMenuStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pnlMenuTeacher.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenuTeacher.setForeground(new java.awt.Color(255, 255, 255));

        lblHeadingPage1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHeadingPage1.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadingPage1.setText("JClassroom");

        btnClasses1.setBackground(new java.awt.Color(0, 0, 0));
        btnClasses1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClasses1.setForeground(new java.awt.Color(255, 255, 255));
        btnClasses1.setText("Classes");
        btnClasses1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnClasses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasses1ActionPerformed(evt);
            }
        });

        btnAssignments1.setBackground(new java.awt.Color(0, 0, 0));
        btnAssignments1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssignments1.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignments1.setText("Assignments");
        btnAssignments1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAssignments1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignments1ActionPerformed(evt);
            }
        });

        btnAddAssignment.setBackground(java.awt.Color.black);
        btnAddAssignment.setForeground(java.awt.Color.white);
        btnAddAssignment.setText("New Assignment");
        btnAddAssignment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAddAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssignmentActionPerformed(evt);
            }
        });

        btnNewClass.setBackground(java.awt.Color.black);
        btnNewClass.setForeground(java.awt.Color.white);
        btnNewClass.setText("New Class");
        btnNewClass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnNewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuTeacherLayout = new javax.swing.GroupLayout(pnlMenuTeacher);
        pnlMenuTeacher.setLayout(pnlMenuTeacherLayout);
        pnlMenuTeacherLayout.setHorizontalGroup(
            pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTeacherLayout.createSequentialGroup()
                .addGroup(pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuTeacherLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblHeadingPage1))
                    .addGroup(pnlMenuTeacherLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAssignments1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addGroup(pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClasses1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewClass, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        pnlMenuTeacherLayout.setVerticalGroup(
            pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTeacherLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblHeadingPage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignments1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClasses1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNewClass, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(btnAddAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );

        pnlCreateClasses.setBackground(java.awt.Color.black);
        pnlCreateClasses.setForeground(new java.awt.Color(255, 255, 255));

        txtClassName.setBackground(java.awt.Color.black);
        txtClassName.setForeground(new java.awt.Color(255, 255, 255));
        txtClassName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassNameActionPerformed(evt);
            }
        });

        btnCreate.setBackground(java.awt.Color.black);
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtClassSubject.setBackground(java.awt.Color.black);
        txtClassSubject.setForeground(new java.awt.Color(255, 255, 255));
        txtClassSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtClassSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassSubjectActionPerformed(evt);
            }
        });

        lblClassName.setBackground(new java.awt.Color(0, 0, 0));
        lblClassName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClassName.setForeground(new java.awt.Color(255, 255, 255));
        lblClassName.setText("Classroom Name");

        lblClassSubject.setBackground(new java.awt.Color(0, 0, 0));
        lblClassSubject.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClassSubject.setForeground(new java.awt.Color(255, 255, 255));
        lblClassSubject.setText("Classroom Subject");

        jLClassList.setBackground(new java.awt.Color(0, 0, 0));
        jLClassList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLClassList.setForeground(new java.awt.Color(255, 255, 255));
        jLClassList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        pnlCreateClassesScrollPanel.setViewportView(jLClassList);

        lblClassSubject1.setBackground(new java.awt.Color(0, 0, 0));
        lblClassSubject1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblClassSubject1.setForeground(new java.awt.Color(255, 255, 255));
        lblClassSubject1.setText("Members");

        javax.swing.GroupLayout pnlCreateClassesLayout = new javax.swing.GroupLayout(pnlCreateClasses);
        pnlCreateClasses.setLayout(pnlCreateClassesLayout);
        pnlCreateClassesLayout.setHorizontalGroup(
            pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                        .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(lblClassName)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateClassesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClassSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClassSubject))
                                .addGap(18, 18, 18)))
                        .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(pnlCreateClassesScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        pnlCreateClassesLayout.setVerticalGroup(
            pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                .addGap(18, 135, Short.MAX_VALUE)
                .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblClassName)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtClassSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCreateClassesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClassSubject)))
                .addGap(26, 26, 26)
                .addComponent(lblClassSubject1)
                .addGap(18, 18, 18)
                .addGroup(pnlCreateClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCreateClassesScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate))
                .addGap(71, 71, 71))
        );

        pnlCreateAssignments.setBackground(new java.awt.Color(0, 0, 0));
        pnlCreateAssignments.setForeground(new java.awt.Color(255, 255, 255));

        lblAssignToClasses.setBackground(new java.awt.Color(0, 0, 0));
        lblAssignToClasses.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAssignToClasses.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignToClasses.setText("Assign to Classes");

        txtAssignmentTitle.setBackground(java.awt.Color.black);
        txtAssignmentTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtAssignmentTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        txtAssignmentTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignmentTitleActionPerformed(evt);
            }
        });

        btnCreateAssignment.setBackground(java.awt.Color.black);
        btnCreateAssignment.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAssignment.setText("Create");
        btnCreateAssignment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCreateAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAssignmentActionPerformed(evt);
            }
        });

        lblAssignmentTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblAssignmentTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAssignmentTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignmentTitle.setText("Assignment Title");

        lblAssignmentDesc.setBackground(new java.awt.Color(0, 0, 0));
        lblAssignmentDesc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAssignmentDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignmentDesc.setText("Assignment Description");

        jlTeacherClasses.setBackground(new java.awt.Color(0, 0, 0));
        jlTeacherClasses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jlTeacherClasses.setForeground(new java.awt.Color(255, 255, 255));
        jlTeacherClasses.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        pnlCreateClassesScrollPanel1.setViewportView(jlTeacherClasses);

        txtAssignmentDesc.setBackground(new java.awt.Color(0, 0, 0));
        txtAssignmentDesc.setColumns(20);
        txtAssignmentDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtAssignmentDesc.setRows(5);

        lblAssignmentDueDate.setBackground(new java.awt.Color(0, 0, 0));
        lblAssignmentDueDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAssignmentDueDate.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignmentDueDate.setText("Due Date:");

        javax.swing.GroupLayout pnlCreateAssignmentsLayout = new javax.swing.GroupLayout(pnlCreateAssignments);
        pnlCreateAssignments.setLayout(pnlCreateAssignmentsLayout);
        pnlCreateAssignmentsLayout.setHorizontalGroup(
            pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(pnlCreateClassesScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                                .addComponent(lblAssignmentDueDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdcDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAssignmentTitle)
                                    .addComponent(lblAssignmentDesc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateAssignmentsLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAssignToClasses)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAssignmentTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(txtAssignmentDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCreateAssignmentsLayout.setVerticalGroup(
            pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                .addGap(18, 170, Short.MAX_VALUE)
                .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignmentTitle)
                    .addComponent(txtAssignmentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreateAssignmentsLayout.createSequentialGroup()
                                .addComponent(lblAssignmentDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAssignToClasses))
                            .addComponent(txtAssignmentDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlCreateClassesScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCreateAssignmentsLayout.createSequentialGroup()
                        .addGroup(pnlCreateAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAssignmentDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdcDueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        pnlClassesStudent.setBackground(new java.awt.Color(0, 0, 0));
        pnlClassesStudent.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlClassesStudentLayout = new javax.swing.GroupLayout(pnlClassesStudent);
        pnlClassesStudent.setLayout(pnlClassesStudentLayout);
        pnlClassesStudentLayout.setHorizontalGroup(
            pnlClassesStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlClassesStudentLayout.setVerticalGroup(
            pnlClassesStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        pnlClassesTeacher.setBackground(new java.awt.Color(0, 0, 0));
        pnlClassesTeacher.setForeground(new java.awt.Color(255, 255, 255));
        pnlClassesTeacher.setToolTipText("");

        javax.swing.GroupLayout pnlClassesTeacherLayout = new javax.swing.GroupLayout(pnlClassesTeacher);
        pnlClassesTeacher.setLayout(pnlClassesTeacherLayout);
        pnlClassesTeacherLayout.setHorizontalGroup(
            pnlClassesTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTeacherClasses, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        pnlClassesTeacherLayout.setVerticalGroup(
            pnlClassesTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spTeacherClasses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlClassesStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlClassesTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCreateClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCreateAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlClassesStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlClassesTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCreateClasses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCreateAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
 /**Create an instance of the DataGenerator class
 
 
 
    DataGenerator dataGenerator = new DataGenerator();
    
   
        for (int i = 0; i < 100; i++) {
            // Generate a fake account    
    Account fakeAccount = dataGenerator.generateFakeAccount();
    
    // Create an instance of the StorageDatabase class
    StorageDatabase storageDatabase = new StorageDatabase();
    
    // Insert the fake account into the database
    storageDatabase.insertAccount(fakeAccount);
    
    // Close the StorageDatabase connection
    storageDatabase.close();
    
    System.out.println("Fake account"+i+" inserted into the database.");
    **/
       System.exit(2);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
pnlHome.setVisible(false);
pnlLogin.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
pnlHome.setVisible(false);
pnlRegister.setVisible(true);
       
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnAgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgreementActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        Date dateOfBirth = yrValue.getDate();
        int age = Integer.parseInt(spnAge.getValue().toString());
        boolean teacherSelected = btnAgreement.isSelected();

        boolean isValid = AccountValidator.validate(username, password, dateOfBirth, age, teacherSelected);

        if (isValid) {
            Account newAccount = new Account(username, password, dateOfBirth, age, teacherSelected);
           
            storage.insertAccount(newAccount);
            
            txtUsername.setText("");
            txtPassword.setText("");
            yrValue.setDate(null);
            spnAge.setValue(0);
            btnAgreement.setSelected(false);
            pnlRegister.setVisible(false);
            pnlHome.setVisible(true);
        }  else {
            // show error message
        }
    }//GEN-LAST:event_btnValidateActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void txtPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassword1ActionPerformed

    private void btnClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassesActionPerformed
 pnlMenuStudent.setVisible(false);
    pnlClassesStudent.setVisible(true);
TabbedPaneGenerator tabbedPaneGenerator = new TabbedPaneGenerator(storage);
    // Retrieve the class names
    String tempusername = storage.getCurrentUsername();
    List<Integer> tempClassIds = storage.getClassIds(tempusername);
    List<String> tempClassNames = new ArrayList<>();
    for (int classId : tempClassIds) {
        String className = storage.getClassName(classId);
        tempClassNames.add(className);
    }

    // Generate the tabbed pane
    JTabbedPane tabbedPane = tabbedPaneGenerator.generateTabbedPane(tempClassNames);

    // Clear the pnlClassesStudent panel before adding the tabbed pane
    pnlClassesStudent.removeAll();

    // Set layout manager for pnlClassesStudent (e.g., if using BorderLayout)
    pnlClassesStudent.setLayout(new BorderLayout());

    // Add the tabbed pane to pnlClassesStudent
    pnlClassesStudent.add(tabbedPane, BorderLayout.CENTER);

    // Refresh the pnlClassesStudent panel to reflect the changes
    pnlClassesStudent.revalidate();
    pnlClassesStudent.repaint();


    }//GEN-LAST:event_btnClassesActionPerformed

    private void btnAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignmentsActionPerformed

       

    }//GEN-LAST:event_btnAssignmentsActionPerformed

    private void btnLoginCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginCheckActionPerformed
            
        String username = txtUsername1.getText();
       storage.setCurrentUsername(username);
        String temp = storage.getCurrentUsername();
        System.out.println(temp);
        String password = new String(txtPassword1.getText());
        
       
        
        // Check if the account exists in the database
        if (storage.checkAccountExists(username, password)) {
            // Determine the account type
            boolean isTeacher = storage.isTeacherAccount(username);
            
            // Redirect to the appropriate panel
            if (isTeacher) {
                pnlMenuTeacher.setVisible(true);
                pnlLogin.setVisible(false);
                
            } else {
                pnlMenuStudent.setVisible(true);
                pnlLogin.setVisible(false);
            }
            
            // Clear the username and password fields
            txtUsername1.setText("");
            txtPassword1.setText("");
        } else {
            System.out.println("The entered username or password is not in the database");
        }
        
       

    }//GEN-LAST:event_btnLoginCheckActionPerformed

    private void btnClasses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasses1ActionPerformed
         pnlMenuTeacher.setVisible(false);
    pnlClassesTeacher.setVisible(true);

   // Create an instance of TabbedPaneGenerator with the StorageDatabase object
TabbedPaneGenerator tabbedPaneGenerator = new TabbedPaneGenerator(storage);

// Retrieve the class names
String tempUsername = storage.getCurrentUsername();
int tempTeacherID = storage.getTeacherIdByUsername(tempUsername);
List<Integer> tempClassIds = storage.getClassIDsByTeacherID(tempTeacherID);
List<String> tempClassNames = new ArrayList<>();
for (int classId : tempClassIds) {
    String className = storage.getClassName(classId);
    tempClassNames.add(className);
}

// Generate the tabbed pane
JTabbedPane tabbedPane = tabbedPaneGenerator.generateTabbedPane(tempClassNames);

// Clear the pnlClassesTeacher panel before adding the tabbed pane
pnlClassesTeacher.removeAll();

// Set layout manager for pnlClassesTeacher (e.g., if using BorderLayout)
pnlClassesTeacher.setLayout(new BorderLayout());

// Add the tabbed pane to pnlClassesTeacher
pnlClassesTeacher.add(tabbedPane, BorderLayout.CENTER);

// Refresh the pnlClassesTeacher panel to reflect the changes
pnlClassesTeacher.revalidate();
pnlClassesTeacher.repaint();
    }//GEN-LAST:event_btnClasses1ActionPerformed

    private void btnAssignments1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignments1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignments1ActionPerformed
private void loadTeacherClassNames() {
    String tempUsername = storage.getCurrentUsername();
    int teacherID = storage.getTeacherIdByUsername(tempUsername);
    List<String> classNames = storage.getTeacherClassNames(teacherID);
    System.out.println(classNames);
    DefaultListModel<String> model = new DefaultListModel<>();
    for (String className : classNames) {
        model.addElement(className);
    }
    jlTeacherClasses.setModel(model);
}

    private void btnAddAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssignmentActionPerformed

    pnlMenuTeacher.setVisible(false);
    pnlCreateAssignments.setVisible(true);

    // Load student names into jLClassList
    loadTeacherClassNames();
    jlTeacherClasses.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
   
    }//GEN-LAST:event_btnAddAssignmentActionPerformed
private void loadStudentNames() {
    
    List<String> studentNames = storage.getStudentNames();
    DefaultListModel<String> model = new DefaultListModel<>();
    for (String studentName : studentNames) {
        model.addElement(studentName);
    }
    jLClassList.setModel(model);
 
}



    private void btnNewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClassActionPerformed
     pnlMenuTeacher.setVisible(false);
    pnlCreateClasses.setVisible(true);

    // Load student names into jLClassList
    loadStudentNames();
    jLClassList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    
    }//GEN-LAST:event_btnNewClassActionPerformed

    private void txtClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    pnlMenuTeacher.setVisible(false);
    pnlCreateClasses.setVisible(true);

    // Get logged in username
    String tempUsername = storage.getCurrentUsername();

    // Create an instance of the Account class
    Account loggedInAccount = new Account(tempUsername, "", null, 0, false);
    // Get the teacher ID
    int teacherId = storage.getTeacherIdByUsername(tempUsername);
    loggedInAccount.setTeacherId(teacherId);
    List<String> selectedStudentNames = jLClassList.getSelectedValuesList();
    // Check if any students are selected
    if (!selectedStudentNames.isEmpty()) {
        // Add the class to the database and assign it to the teacher or student
        String className = txtClassName.getText();
        String classSubject = txtClassSubject.getText();
        if (loggedInAccount.isTeacher()) {
            storage.insertClassroom(className, classSubject, teacherId);
        } else {
            storage.insertClassroom(className, classSubject, teacherId);
        }

        int classId = storage.getClassIdByName(className);

        // Retrieve the student IDs based on the selected student names
        List<Integer> studentIds = storage.getStudentIdsByNames(selectedStudentNames);
        storage.addToClassList(classId, studentIds);
        System.out.println(studentIds);
      
    } else {
        System.out.println("No students selected.");
    }


}

// Method to retrieve the currently logged-in teacher's username
private String getCurrentTeacherUsername() {
    // Add your code to retrieve the currently logged-in teacher's username
    // and return it here
    // For demonstration purposes, let's assume the username is stored in a variable called "loggedInTeacherUsername"
    String loggedInTeacherUsername = "teacher1";
    return loggedInTeacherUsername;
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtClassSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassSubjectActionPerformed

    private void txtAssignmentTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignmentTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignmentTitleActionPerformed

    private void btnCreateAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAssignmentActionPerformed
        String selectedClass = jlTeacherClasses.getSelectedValue();
        System.out.println(selectedClass);
        int ClassID = storage.getClassIdByName(selectedClass);
        System.out.println(ClassID);
        String assTitle = txtAssignmentTitle.getText();
        System.out.println(assTitle);
        String assDesc = txtAssignmentDesc.getText();
        System.out.println(assDesc);
        String tempUsername = storage.getCurrentUsername();
        int TeacherID = storage.getTeacherIdByUsername(tempUsername);
        Date DueDate = jdcDueDate.getDate();
        System.out.println(DueDate);
        int StudentId = 0;
        storage.addAssignment(ClassID, TeacherID, StudentId, assTitle, assDesc, DueDate);
    }//GEN-LAST:event_btnCreateAssignmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAssignment;
    private javax.swing.JCheckBox btnAgreement;
    private javax.swing.JButton btnAssignments;
    private javax.swing.JButton btnAssignments1;
    private javax.swing.JButton btnClasses;
    private javax.swing.JButton btnClasses1;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateAssignment;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginCheck;
    private javax.swing.JButton btnNewClass;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnValidate;
    private javax.swing.JList<String> jLClassList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcDueDate;
    private javax.swing.JList<String> jlTeacherClasses;
    private javax.swing.JLabel lblAssignToClasses;
    private javax.swing.JLabel lblAssignmentDesc;
    private javax.swing.JLabel lblAssignmentDueDate;
    private javax.swing.JLabel lblAssignmentTitle;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblClassSubject;
    private javax.swing.JLabel lblClassSubject1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHeader1;
    private javax.swing.JLabel lblHeadingPage;
    private javax.swing.JLabel lblHeadingPage1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JPanel pnlClassesStudent;
    private javax.swing.JPanel pnlClassesTeacher;
    private javax.swing.JPanel pnlCreateAssignments;
    private javax.swing.JPanel pnlCreateClasses;
    private javax.swing.JScrollPane pnlCreateClassesScrollPanel;
    private javax.swing.JScrollPane pnlCreateClassesScrollPanel1;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMenuStudent;
    private javax.swing.JPanel pnlMenuTeacher;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JScrollPane spTeacherClasses;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextArea txtAssignmentDesc;
    private javax.swing.JTextField txtAssignmentTitle;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtClassSubject;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    private com.toedter.calendar.JDateChooser yrValue;
    // End of variables declaration//GEN-END:variables

}
